- HowTo/initial-setup.md
- README.md
- configServer.h
> extended the options

- .github/workflows/ci.yml
- README.md
Added two small badges for the Readme:
- Build status of the latest commit (CI)
- Latest version number (automatically uses last Github Release)
> CI & version badge for Readme

- .github/workflows/ci.yml
- OpenBikeSensorFirmware/OpenBikeSensorFirmware.ino
- platformio.ini
Leverage github actions for automated release build.
> Publish result with unique version

- OpenBikeSensorFirmware/OpenBikeSensorFirmware.ino
- OpenBikeSensorFirmware/displays.cpp
- OpenBikeSensorFirmware/displays.h
- OpenBikeSensorFirmware/gps.cpp
we receive 2 messages (GPRMC && GPGGA - both below 80 byte) per second.
we need to be able to buffer 2 times the full data - since we might get 2
data sets in one loop (we need a bit more than 1 second to process out loop)
2 * 2 * 80 == 320 -> which is < 128+256 -> but it is split in the 2 buffers then,
I've increased the RX buffer to 512 for now (see OpenBikeSensorFirmware#setup)
- Static Hold 0.8m/s / UBX-CFG-NAV5
- https://portal.u-blox.com/s/question/0D52p00008HKEE8/best-cfgnav5-and-cfgodo-configuration-for-my-application
From the spec: _**Pedestrian**: Applications with low acceleration and speed, e.g. how a pedestrian would move. Low
acceleration assumed. MAX Altitude [m]: 9000, MAX Velocity [m/s]: 30, MAX Vertical
Velocity [m/s]: 20, Sanity check type: Altitude and Velocity, Max …
> Tweek some GPS settings.

- .github/README-release.md
- .github/workflows/ci.yml
- .idea/OpenBikeSensorFirmware.iml
- .idea/misc.xml
- OpenBikeSensorFirmware/OpenBikeSensorFirmware.cpp
- OpenBikeSensorFirmware/VoltageMeter.cpp
- OpenBikeSensorFirmware/VoltageMeter.h
- OpenBikeSensorFirmware/bluetooth/BluetoothManager.cpp
- OpenBikeSensorFirmware/config.cpp
- OpenBikeSensorFirmware/config.h
- OpenBikeSensorFirmware/configServer.cpp
- OpenBikeSensorFirmware/displays.cpp
- OpenBikeSensorFirmware/displays.h
- OpenBikeSensorFirmware/globals.h
- OpenBikeSensorFirmware/gps.cpp
- OpenBikeSensorFirmware/gps.h
- OpenBikeSensorFirmware/sensor.cpp
- OpenBikeSensorFirmware/sensor.h
- OpenBikeSensorFirmware/uploader.cpp
- OpenBikeSensorFirmware/writer.cpp
- OpenBikeSensorFirmware/writer.h
- docs/software/firmware/csv_format.md
- open-bike-sensor.code-workspace
See the created docs/software/firmware/csv_format.md for a start of the discussion.
Also consider how the frontends can be adjusted, there will definitely be a (longer) time where both formats need to be supported. I hope I've addressed all points from our discussion.
> Initial proposal for a new CVS data format. Fixes #144

- OpenBikeSensorFirmware/configServer.cpp
A very simple UI that displays file on the SD card and allows to download them. It looks like this:
> Serve contents of SD card through config server

- src/writer.cpp
> Do not write course and speed in privacy area

- .github/workflows/ci.yml
* SonarQube integration, cache tool installation
* Release, collect git commit comments in draft release.
> Improve ci build

- .idea/modules.xml
- docs/software/firmware/csv_format.md
- src/OpenBikeSensorFirmware.cpp
- src/VoltageMeter.cpp
- src/configServer.cpp
- src/uploader.cpp
- src/utils/file.cpp
- src/utils/file.h
- src/utils/streams.cpp
- src/writer.cpp
- src/writer.h
> Change filename once we know the time

- .github/workflows/ci.yml
- src/configServer.cpp
Different way to retry depending on the error we get - we still give up after 10 seconds and switch to the AP mode.
This fixes #120
> Retry WiFi connection if it does not succeed in the 1st try.

- platformio.ini
- src/OpenBikeSensorFirmware.cpp
- src/configServer.cpp
- src/gps.cpp
- src/sensor.cpp
- src/sensor.h
- src/utils/obsutils.cpp
- src/utils/obsutils.h
- avoid duplicate content in const strings
- move style to header for faster rendering
- Add a title to each page (#141)
- "Stream" upload page while uploading
- Show upload results in upload page (fixes #109)
- "Stream" SD directory page
- Add content-type for cvs in download
- Refine `/` handling in SD download
- Add icons to SD file browser
- back arrow calls history.back()
- html cleanup
- read GPS always and early in config mode
- add system info page
- Place "Upload Track" at top (fixes #167)
- Collect TOF sensor statistics and display them on the about page
There are other things todo but this is already a large PR.
> Several refinements in configServer

- src/OpenBikeSensorFirmware.cpp
- src/configServer.cpp
- src/configServer.h
- src/displays.h
- src/globals.h
- src/gps.cpp
- src/sensor.cpp
- src/sensor.h
- src/uploader.cpp
- src/uploader.h
- src/utils/median.h
- src/utils/multipart.cpp
- src/utils/multipart.h
- src/utils/obsutils.cpp
- src/utils/obsutils.h
- src/utils/streams.cpp
- src/utils/streams.h
> Allow track upload with just a long button press in server mode

- src/OpenBikeSensorFirmware.cpp
- src/config.cpp
- src/configServer.cpp
- src/displays.cpp
- src/displays.h
- src/globals.h
- src/gps.cpp
- src/gps.h
> refactor GPS code to use own class

- .idea/OpenBikeSensorFirmware.iml
- src/OpenBikeSensorFirmware.cpp
- src/VoltageMeter.cpp
- src/VoltageMeter.h
- src/displays.cpp
- src/displays.h
- src/gps.cpp
> Early at power up warning if battery voltage is low

- README.md
- src/Firmware.cpp
- src/Firmware.h
- src/OpenBikeSensorFirmware.cpp
- src/configServer.cpp
- src/gps.cpp
- src/utils/obsutils.cpp
- src/utils/obsutils.h
⚠️ Ready for testing. Note that you need to flash via USB cable to go back to the old partitioning schema or if things go wrong.
⚠️ Documentation see Updating at https://github.com/openbikesensor/OpenBikeSensorFirmware/blob/feature/flash-sd/README.md
> Use asymetric ota process to gain flash memory space

- src/OpenBikeSensorFirmware.cpp
- src/utils/obsutils.cpp
- src/writer.h
Fixes #253 - Confirmed pass events are not always visible in csv
> Fix: Ensure confirmed pass event is not lost when new event pending

- src/OpenBikeSensorFirmware.cpp
- src/configServer.cpp
- src/globals.h
- src/utils/button.cpp
- src/utils/button.h
- src/writer.cpp
> Debounce button read

- src/OpenBikeSensorFirmware.cpp
- src/obsimprov.cpp
- src/obsimprov.h
uses https://github.com/improv-wifi/website/issues/16
> Allow to query visible SSIDs via improv

- docs/software/firmware/csv_format.md
> Correct Typo in title

- docs/software/firmware/obs_cfg.md
- src/OpenBikeSensorFirmware.cpp
- src/config.cpp
- src/config.h
- src/configServer.cpp
> Drop dedicated SimRa mode, simply enable Bluetooth for SimRa

- src/configServer.cpp
This improves readability on smartphones because the menu is not tiny any more but fills the screen.
> Adapt menu to display size
